### ISSUE TITLE
An erroneous output for modbus??

### ISSUE THREAD

**Issue by blueclowd** [188080501/JQChecksum#1]
Input: 010600050035
Output: 59dc

But the output should be 59C7.
Could you please help to check this. Thanks

**Comment by 188080501** [comment]
不好意思，前段时间比较忙，一直没来回复
我现在去看下什么情况

**Comment by 188080501** [comment]
我找了4个在线计算器，算出来全部都是59DC

![2017-07-24 14 33 38](https://user-images.githubusercontent.com/6997074/28510917-44d8ae9e-707d-11e7-876c-060134598aaf.png)
![2017-07-24 14 33 45](https://user-images.githubusercontent.com/6997074/28510918-454ee924-707d-11e7-8cbf-b2ab0d8f0875.png)
![2017-07-24 14 33 51](https://user-images.githubusercontent.com/6997074/28510919-4553160c-707d-11e7-8b67-062d920af610.png)
![2017-07-24 14 34 25](https://user-images.githubusercontent.com/6997074/28510920-45612b48-707d-11e7-875c-ac1c5bc3730a.png)

**Comment by 188080501** [comment]
你的59C7，不是我们常说的modbus标准算出来的结果
是另外一个标准算出来的结果，请复查

另外我截图里也有59C7这个数据，但是都不属于modbus这个分类。
